### ISSUE TITLE
Pos widget conflicts with bootstrap

### ISSUE THREAD

**Issue by saxering** [turinglabsorg/block-bitcoin-pos#1]
Good evening. I recently added Block! Pos to my organization's site to collect donations. The template of this site is bootstrap based. I followed the instructions on your site and the payment button appears as expected. The problem starts after I clicked it: the widget that let me insert the amount to send appears, but it conflicts with some css of the page, maybe some "position" directive. I solved just creating a fake payment button that programmatically calls the click event on the real button, added directly in the body tag, outside every other tag of the page. This issue took me some time to solve. Anyway, if you can't solve this issue adapting the javascript code, please document it, so site developers can go smoothly in integration of this very good service.
Thanks a lot!

**Comment by turinglabsorg** [comment]
I've just seen the issue, the project is not actively maintained but i will write this information in the website, thank you
